# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

title:    Minimal GitHub Pages Jekyll
url:      https://matita.github.io
baseurl:  /min-gh-jekyll

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
