# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

title:    Minimal GitHub Pages Jekyll
url:      https://matita.github.io
baseurl:  /min-gh-jekyll
permalink:  /link/:title

ghuser:   matita

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"
